#!/bin/bash

DATE=`date +%d%m%Y.%H%M%S`;

while true ;
	do
	   echo "***********************************" >>/home/android/wifi_scan_logfile_$DATE ;
	   date >> /home/android/wifi_scan_logfile_$DATE ;
	   iwlist wlan0 scan | grep -E "Cell|SSID|IE" >> /home/android/wifi_scan_logfile_$DATE ;
	 	sleep 5;
	 done
